name: iOS testing with xchelper action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: swiftlint
        uses: BlueIntent/iOS-helper-action@v1.0
        with:
          action: 'swiftlint'
      - name: pod lib lint
        uses: BlueIntent/iOS-helper-action@v1.0
        with:
          action: 'pod-lib-lint'
      - name: install
        uses: BlueIntent/iOS-helper-action@v1.0
        with:
          action: 'install'
      - name: test
        uses: BlueIntent/iOS-helper-action@v1.0
        with:
          action: 'test'
